[package]
name = "pagemap"
version = "0.1.0"
authors = ["Christos Katsakioris <ckatsak@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
libc = "0.2"
thiserror = "1.0"

[dev-dependencies]
anyhow = "1"
